// This file is auto-generated by scripts/generate-models.ts
// 中文说明：本文件由 scripts/generate-models.ts 自动生成。
// Do not edit manually - run 'npm run generate-models' to update
// 中文说明：禁止手工修改；需要更新时请运行 npm run generate-models。
/**
 * 文件职责：保存单个供应商的模型目录分片，或汇总所有供应商分片形成统一模型索引。
 * 技术维度：使用 TypeScript 静态类型、JSON 导入属性和 flattenModelCatalog 将生成数据转换为只读模型目录。
 * 产品维度：为模型选择、能力判断和请求路由提供内置模型清单，使用户无需手工录入常见供应商模型。
 * 逻辑维度：供应商分片加载对应 JSON 并扁平化；聚合文件导入全部分片，再按供应商标识组成 MODELS 对象。
 * 关键边界：内容来自外部目录与生成器修正规则，禁止手工编辑；任何调整都必须修改生成器后重新生成并校验。
 * 新手阅读建议：先确认这是生成文件，再查看导入的数据分片和导出常量；业务规则应回到 generate-models.ts 阅读。
 */

import values from "./data/vercel-ai-gateway.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

/** 当前供应商的只读模型目录；键为模型 ID，值为经过扁平化和类型校验的模型元数据。 */
export const VERCEL_AI_GATEWAY_MODELS: ModelCatalog<typeof values, "vercel-ai-gateway"> =
	flattenModelCatalog("vercel-ai-gateway", values);
